version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./postgres.env
    volumes:
      - ./app_data:/var/lib/postgresql/data
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
      
  redis:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - redis:/data
    ports:
     - "6379:6379"
     
  # chromedriver:
    # image: robcherry/docker-chromedriver
    
  # chrome:
        # image: selenium/standalone-chrome:latest
        # hostname: chrome
        # privileged: true
        # shm_size: 2g  
 
  superset:
    container_name: superset
    image: amancevice/superset
    restart: always
    depends_on:
      - postgres
      - redis
      #- chromedriver
      #- chrome
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
    environment:
      - SQLALCHEMY_DATABASE_URI='postgresql://cps1:12345@postgres/superset'
      - SUPERSET_FEATURE_EMBEDDED_SUPERSET='true'  
  
volumes:
  postgres:
  redis:
  superset: